// This file is auto-generated by @hey-api/openapi-ts

export type GoogleMaps = {
    apiKey?: string | null;
    defaultLocation?: string | null;
    zoomLevel?: number | null;
};

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: GoogleMaps;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44325' | (string & {});
};