name: Our.Umbraco.GMaps - CI

on:
  pull_request:

env:
  SOLUTION: Our.Umbraco.GMaps.Release.sln
  OUTPUT_PATH: ${{ github.workspace }}/.output

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['9.x']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Support @umbraco-cms/backoffice@16.0.0 requires node >= 22
    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
      
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3

      with:
        dotnet-version: ${{ matrix.dotnet-version }}
  
    - name: Install dependencies
      run: dotnet restore ${{ env.SOLUTION }}
  
    - name: Build
      run: dotnet build ${{ env.SOLUTION }} --no-restore --configuration Release
        
    - name: Create the package
      run: dotnet pack ${{ env.SOLUTION }} --no-build --no-restore --configuration Release --property:PackageOutputPath=${{ env.OUTPUT_PATH }}
      # https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/7.0/solution-level-output-no-longer-valid
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: ${{ env.OUTPUT_PATH }}/