name: Our.Umbraco.GMaps - CI

on:
  pull_request:

env:
  CLIENT_PROJECT: Our.Umbraco.GMaps/Client
  PLUGIN_PROJECT: Our.Umbraco.GMaps/Our.Umbraco.GMaps.csproj
  OUTPUT_PATH: ./build-out/

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['9.x']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
      
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4

      with:
        dotnet-version: ${{ matrix.dotnet-version }}
  
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '${{env.CLIENT_PROJECT}}/package.json'
        cache: 'npm'
        cache-dependency-path: '${{env.CLIENT_PROJECT}}/package-lock.json'

    - name: Install Node dependencies
      run: npm ci
      working-directory: ${{env.CLIENT_PROJECT}}

    - name: Build Client
      run: npm run build
      working-directory: ${{env.CLIENT_PROJECT}}
  
    - name: Build
      run: dotnet build ${{ env.PLUGIN_PROJECT }} --configuration Release
        
    - name: Create the package
      run: dotnet pack ${{ env.PLUGIN_PROJECT }} --no-build --no-restore --configuration Release -o ${{ env.OUTPUT_PATH }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: ${{ env.OUTPUT_PATH }}/